-- GuruKhata — Postgres schema v1 (from docs/ARCHITECTURE.md "Data model (v1)").
-- Idempotent: IF NOT EXISTS everywhere, safe to re-apply:
--   psql "$DATABASE_URL" -f db/schema.sql
--
-- MULTI-TENANT RULE #1: every tenant query is scoped WHERE tutor_id = $1
-- (directly, or via the owning student/due). See api/src/db.js.

-- ---------------------------------------------------------------------------
-- tutors — one row per teacher (the tenant). Rohan's google_sub seeded admin.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tutors (
  id              BIGSERIAL PRIMARY KEY,
  google_sub      TEXT NOT NULL UNIQUE,          -- Google account subject id
  name            TEXT,
  phone           TEXT,
  upi_id          TEXT,                          -- interpolated into reminders
  language_pref   TEXT NOT NULL DEFAULT 'en',    -- 'en' | 'hi' (template lang)
  tone_pref       TEXT,
  role            TEXT NOT NULL DEFAULT 'tutor'
                  CHECK (role IN ('tutor', 'admin')),
  plan            TEXT NOT NULL DEFAULT 'free'
                  CHECK (plan IN ('free', 'paid')),   -- Phase 4
  plan_expires_at TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_active_at  TIMESTAMPTZ
);

-- ---------------------------------------------------------------------------
-- students — minors: keep PII minimal (name only; parent name + phone).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS students (
  id           BIGSERIAL PRIMARY KEY,
  tutor_id     BIGINT NOT NULL REFERENCES tutors(id) ON DELETE CASCADE,
  name         TEXT NOT NULL,
  parent_name  TEXT,
  parent_phone TEXT,                              -- 10-digit Indian mobile
  subject      TEXT,                              -- plain string in v1 (no batches)
  monthly_fee  NUMERIC(10, 2) NOT NULL DEFAULT 0,
  due_day      SMALLINT NOT NULL DEFAULT 1
               CHECK (due_day BETWEEN 1 AND 31),
  active       BOOLEAN NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_students_tutor_id ON students (tutor_id);

-- ---------------------------------------------------------------------------
-- dues — one row per student per month, generated by the monthly cron with
-- INSERT ... ON CONFLICT DO NOTHING (UNIQUE below makes re-runs harmless).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS dues (
  id         BIGSERIAL PRIMARY KEY,
  student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  month      TEXT NOT NULL CHECK (month ~ '^\d{4}-\d{2}$'),  -- '2026-10'
  amount     NUMERIC(10, 2) NOT NULL,
  status     TEXT NOT NULL DEFAULT 'due'
             CHECK (status IN ('due', 'paid', 'waived')),
  paid_at    TIMESTAMPTZ,
  receipt_no TEXT,                                -- per-tutor sequence, 'TUT-2026-0042'
  UNIQUE (student_id, month)
);

-- Overdue list + "dues created vs paid" admin stats scan by status within a month.
CREATE INDEX IF NOT EXISTS idx_dues_status_month ON dues (status, month);

-- ---------------------------------------------------------------------------
-- reminders — audit of every nudge sent for a due.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS reminders (
  id            BIGSERIAL PRIMARY KEY,
  due_id        BIGINT NOT NULL REFERENCES dues(id) ON DELETE CASCADE,
  sent_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  channel       TEXT NOT NULL CHECK (channel IN ('wa_link', 'push', 'api')),
  template_used TEXT
);

CREATE INDEX IF NOT EXISTS idx_reminders_due_id ON reminders (due_id);

-- ---------------------------------------------------------------------------
-- push_subs — Web Push (VAPID) subscriptions per tutor.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS push_subs (
  id         BIGSERIAL PRIMARY KEY,
  tutor_id   BIGINT NOT NULL REFERENCES tutors(id) ON DELETE CASCADE,
  endpoint   TEXT NOT NULL,
  keys_json  JSONB NOT NULL,                      -- { p256dh, auth }
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_push_subs_tutor_id ON push_subs (tutor_id);

-- ---------------------------------------------------------------------------
-- admin_log — audit rule: EVERY admin write (plan change, deactivate, …)
-- inserts a row here.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_log (
  id       BIGSERIAL PRIMARY KEY,
  admin_id BIGINT NOT NULL REFERENCES tutors(id),
  action   TEXT NOT NULL,                         -- e.g. 'plan_change', 'deactivate'
  target   TEXT,                                  -- e.g. 'tutor:42'
  at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- batches — Phase 2.1. No batches/classes table in v1: students.subject
-- (plain string) is enough for 10-50 students. When the 25-60 student batch
-- segment lands, create this and add students.batch_id.
-- ---------------------------------------------------------------------------
-- CREATE TABLE IF NOT EXISTS batches (
--   id         BIGSERIAL PRIMARY KEY,
--   tutor_id   BIGINT NOT NULL REFERENCES tutors(id) ON DELETE CASCADE,
--   name       TEXT NOT NULL,
--   subject    TEXT,
--   created_at TIMESTAMPTZ NOT NULL DEFAULT now()
-- );
-- ALTER TABLE students ADD COLUMN IF NOT EXISTS batch_id BIGINT REFERENCES batches(id);
